### ISSUE TITLE
Running in TravisCI?

### ISSUE THREAD

**Issue by peteruithoven** [elementary/vala-lint#44]
One of the  great potentials for this linter is in automatically checking pull requests for code style issues. 
I have no experience with setting up CI but looking into this I came to the following `travis.yml`:

``` yml
language: generic

services:
 - docker

env:
 - DEPENDENCY_PACKAGES="meson libgee-0.8-dev valac git"

install:
 - docker pull elementary/docker:loki
 - docker run -v "$PWD":/tmp/build-dir elementary/docker:loki /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/ && git clone https://github.com/peteruithoven/vala-lint.git --branch 3-phases &&  cd vala-lint && meson build --prefix=/usr && cd build && ninja && ./io.elementary.vala-lint -d /tmp/build-dir/src"

script:
 - echo BUILDS PASSED

```

This get's the linter from git, but eventually we'll probably find a better way to distribute the linter. The bigger issue I think is that all the important code is in one big string, given to the docker run command. This makes it hard to read, error prone etc. The reason why is that you build and test in the target environment: elementary OS. 

What would be a better way of doing this?

There is this open TravisCI issue on custom build images, which might be a great solution?
https://github.com/travis-ci/travis-ci/issues/7726

Should we create a specific Docker image which already includes the linting tool?
